// RootLens C2PA 署名用の公開証明書チェーン (= EE + Root、 Ed25519 自己署名)。
//
// 公開情報なのでコードに埋め込む (= 秘密鍵は C2PA_SIGN_KEY_B64 env のみ)。
// C2PA manifest の x5chain に埋まる。 検証側では signingCredential.untrusted 扱い
// (= C2PA trust list 未登録の自己署名) だが、 完全性検証 (bmffHash / claim) は全て通る。
// 公的 CA 発行証明書へ格上げする時はこのチェーンと env の鍵を差し替えるだけ (= アプリ再配布不要)。
//
// profile (= c2pa-rs の署名時証明書検査を通る形):
//   EE:  KU=critical digitalSignature,nonRepudiation / EKU=emailProtection / CA:FALSE
//   Root: KU=critical digitalSignature,keyCertSign / CA:TRUE

export const C2PA_SIGN_CERTS_PEM = `-----BEGIN CERTIFICATE-----
MIIBmTCCAUugAwIBAgIUIyEE/E8RII0DZ78Wz5VtkJaCbKwwBQYDK2VwMDAxETAP
BgNVBAoMCFJvb3RMZW5zMRswGQYDVQQDDBJSb290TGVucyBDMlBBIFJvb3QwHhcN
MjYwNzA0MDQxMTE5WhcNMzEwNzAzMDQxMTE5WjAyMREwDwYDVQQKDAhSb290TGVu
czEdMBsGA1UEAwwUUm9vdExlbnMgQzJQQSBTaWduZXIwKjAFBgMrZXADIQCYzQoN
RWsovgfZOpPr4W65u7gNhGhmnB7nSGn1aI4KcKN1MHMwDAYDVR0TAQH/BAIwADAO
BgNVHQ8BAf8EBAMCBsAwEwYDVR0lBAwwCgYIKwYBBQUHAwQwHQYDVR0OBBYEFOx6
3Z/98i2Bs2yc75lJg1B9rlifMB8GA1UdIwQYMBaAFMTNRmDIke7lWZCUloapwvOO
4+lZMAUGAytlcANBAIxeXPBjHA8YY1zBsiywfAzKALMxc5sSCRSQ3m05eTNMix8d
/9GBMWTYc+CeCalIPdiET5kyGlQNkviwLwL8jgc=
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIBhTCCATegAwIBAgIUWS22f4A62FSvf/BKBgI1WMWQ8mYwBQYDK2VwMDAxETAP
BgNVBAoMCFJvb3RMZW5zMRswGQYDVQQDDBJSb290TGVucyBDMlBBIFJvb3QwHhcN
MjYwNzA0MDQxMTE5WhcNMzYwNzAxMDQxMTE5WjAwMREwDwYDVQQKDAhSb290TGVu
czEbMBkGA1UEAwwSUm9vdExlbnMgQzJQQSBSb290MCowBQYDK2VwAyEAw1WomT7Q
R9DpUiZJG0lGME9eNzT1wb43AQ2Tva6fPpmjYzBhMB0GA1UdDgQWBBTEzUZgyJHu
5VmQlJaGqcLzjuPpWTAfBgNVHSMEGDAWgBTEzUZgyJHu5VmQlJaGqcLzjuPpWTAP
BgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIChDAFBgMrZXADQQBSolz8bXXo
p0IBORs/MRpfFDtIWmAG9gh8wY6PCjkzcLRiyOFJEaXIA4K3ZloucBOH+cW6T7j2
4xhSEL4CrrEB
-----END CERTIFICATE-----
`;
