"""Remove R7's old forehead region and replace it with one generated surface.

The three Boolean operands are generated by RootaCap_R7_forehead_replacement.scad:
an ellipsoidal removal mask, a square-bottom replacement shell, and shallow
M4-head recess cutters.  The recesses are cut only after the shell joins the
body so no underlying support material can refill them.  Blender's manifold
Boolean solver keeps the final mesh a single watertight solid without stacked
or coincident contact surfaces.
"""

from pathlib import Path
import sys

import bmesh
import bpy


def script_args() -> tuple[Path, Path, Path, Path, Path, Path]:
    argv = sys.argv
    if "--" not in argv or len(argv[argv.index("--") + 1 :]) != 6:
        raise SystemExit(
            "usage: blender --background --python rebuild_r7_forehead.py -- "
            "BODY MASK REPLACEMENT COUNTERBORES OUTPUT_STL OUTPUT_BLEND"
        )
    values = [Path(value).resolve() for value in argv[argv.index("--") + 1 :]]
    return values[0], values[1], values[2], values[3], values[4], values[5]


def import_stl(path: Path, name: str) -> bpy.types.Object:
    bpy.ops.wm.stl_import(filepath=str(path))
    obj = bpy.context.active_object
    obj.name = name
    return obj


def apply_boolean(
    body: bpy.types.Object,
    operand: bpy.types.Object,
    operation: str,
    name: str,
) -> None:
    bpy.context.view_layer.objects.active = body
    modifier = body.modifiers.new(name=name, type="BOOLEAN")
    modifier.operation = operation
    modifier.solver = "MANIFOLD"
    modifier.operand_type = "OBJECT"
    modifier.object = operand
    bpy.ops.object.modifier_apply(modifier=modifier.name)


def topology(mesh: bpy.types.Mesh) -> tuple[int, int, int, float]:
    bm = bmesh.new()
    bm.from_mesh(mesh)
    boundary = sum(edge.is_boundary for edge in bm.edges)
    non_manifold = sum(not edge.is_manifold for edge in bm.edges)
    volume = bm.calc_volume(signed=False)
    islands = 0
    remaining = set(bm.verts)
    while remaining:
        islands += 1
        stack = [remaining.pop()]
        while stack:
            vertex = stack.pop()
            for edge in vertex.link_edges:
                other = edge.other_vert(vertex)
                if other in remaining:
                    remaining.remove(other)
                    stack.append(other)
    bm.free()
    return boundary, non_manifold, islands, volume


(
    body_path,
    mask_path,
    replacement_path,
    counterbores_path,
    output_stl,
    output_blend,
) = script_args()

bpy.ops.object.select_all(action="SELECT")
bpy.ops.object.delete(use_global=False)
body = import_stl(body_path, "RootaCap_R7_rebuilt_forehead")
mask = import_stl(mask_path, "Old_forehead_and_headward_removal_mask")
replacement = import_stl(replacement_path, "Generated_square_lower_forehead_surface")
counterbores = import_stl(counterbores_path, "M4_head_recess_cutters")

# Remove the old tile and every possible intrusion toward the forehead.
apply_boolean(body, mask, "DIFFERENCE", "Remove_old_forehead_region")

# Eliminate the two lower-block ends that extended past the original 96 mm fit.
bpy.ops.mesh.primitive_cube_add(location=(0.0, 0.0, 0.0))
width_crop = bpy.context.active_object
width_crop.name = "Width_crop_96mm"
width_crop.dimensions = (96.0, 300.0, 300.0)
bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
apply_boolean(body, width_crop, "INTERSECT", "Crop_width_to_96mm")

# Add one newly generated contact shell; no part of the old contact surface is
# used to fill or patch the replacement.
apply_boolean(body, replacement, "UNION", "Install_generated_forehead_surface")

# Cut the shallow recesses from the completed union.  This order removes both
# the new forehead shell and any supporting material that overlaps its back.
apply_boolean(body, counterbores, "DIFFERENCE", "Cut_M4_head_recesses")

for operand in (mask, replacement, counterbores, width_crop):
    bpy.data.objects.remove(operand, do_unlink=True)

body.data.validate(verbose=True, clean_customdata=True)
body.data.update()
boundary, non_manifold, islands, volume = topology(body.data)
print(
    "R7_REBUILD",
    f"vertices={len(body.data.vertices)}",
    f"polygons={len(body.data.polygons)}",
    f"boundary_edges={boundary}",
    f"non_manifold_edges={non_manifold}",
    f"islands={islands}",
    f"volume_mm3={volume:.6f}",
    f"dimensions_mm={tuple(round(value, 6) for value in body.dimensions)}",
)
if boundary or non_manifold or islands != 1:
    raise SystemExit("rebuilt result is not one closed manifold")

bpy.ops.object.select_all(action="DESELECT")
body.select_set(True)
bpy.context.view_layer.objects.active = body
bpy.ops.wm.stl_export(
    filepath=str(output_stl),
    export_selected_objects=True,
    apply_modifiers=True,
    ascii_format=False,
)
bpy.ops.wm.save_as_mainfile(filepath=str(output_blend))
